# Start from latest alpine parent image
FROM alpine:latest

# Set the working directory
WORKDIR /myapp

# Copy the hellogo app from current directory to container
COPY hellogo .

# Start the application
ENTRYPOINT ["./hellogo"]